### ISSUE TITLE
Usar o .env

### ISSUE THREAD

**Issue by Camilotk** [msena98/weather-master-app#1]
Sua chave da API no front-end está exposta é uma boa prática usar arquivos .env para informações que sejam sensíveis como senhas, chaves de api e etc.

## Links Uteis
- [Código fonte do projeto](https://github.com/motdotla/dotenv)
- [Como usar dotenv no JS](https://blog.rocketseat.com.br/variaveis-ambiente-nodejs/)

**Comment by msena98** [comment]
Certo!

Achei muito interessante os conteúdos, muito obrigado pela dica!

Já estou implementando o uso do dotenv ;D
